# Generated by Django 5.0.6 on 2024-05-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoAusencia', models.TextField()),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ControlDeAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeAusencias', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('anyo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=9)),
                ('fechaNacimineto', models.DateField()),
                ('dui', models.CharField(max_length=10)),
                ('gradoAcademico', models.CharField(max_length=50)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.TextField()),
                ('sexo', models.CharField(max_length=9)),
                ('nacionalidad', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('justificacion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldoNeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuentoAfp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuentoIsss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuentoAusencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalDescuentos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horaExtraDia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horaExtraNoche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldoBruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.planilla')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numReporte', models.IntegerField()),
                ('descripcionReporte', models.TextField()),
                ('fechaReporte', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSolicitud', models.IntegerField()),
                ('fechaSolicitud', models.DateField(auto_now_add=True)),
                ('estadoSolicitud', models.CharField(max_length=8)),
                ('ausencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ausencia')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('paswword', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
