# Generated by Django 5.0.6 on 2024-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ausencia_motivoausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='motivoAusencia',
            field=models.CharField(max_length=50),
        ),
    ]
