# Generated by Django 5.0.6 on 2024-05-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ausencia_motivoausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estadoSolicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='revision', max_length=9),
        ),
    ]
