# Generated by Django 5.0.6 on 2024-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_solicitud_estadosolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
