# Generated by Django 5.0.6 on 2024-06-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_solicitud_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
