# Generated by Django 5.0.6 on 2024-06-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_solicitud_comprobante_ausencia_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
