# Generated by Django 5.0.6 on 2024-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_ausencia_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horaExtraDia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horaExtraNoche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
