# Generated by Django 5.0.6 on 2024-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='monto_total_bonos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
